# components.py
# Reusable Streamlit UI building blocks.
# Each function draws one section of the app.


import streamlit as st
from datetime import datetime
import re


def _clean(text: str) -> str:
    """Strip markdown and encode to ASCII-safe string for PDF."""
    for old, new in [('\u2019',"'"),('\u2018',"'"),('\u201c','"'),('\u201d','"'),
                     ('\u2013','-'),('\u2014','-'),('\u2022','-'),('\u2026','...')]:
        text = text.replace(old, new)
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*',     r'\1', text)
    text = re.sub(r'`(.+?)`',       r'\1', text)
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    return text.encode('ascii', 'ignore').decode('ascii').strip()


def _mcell(pdf, w, h, txt, lm):
    """Safe multi_cell that always resets X to left margin before writing."""
    pdf.set_x(lm)
    pdf.multi_cell(w, h, txt)


def _generate_pdf(report: str, query: str) -> bytes:
    """Convert markdown report to a clean PDF. Returns bytes."""
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_font("Helvetica", size=10)   # must be before add_page in v2.8+
        pdf.set_auto_page_break(auto=True, margin=18)
        pdf.add_page()
        lm = pdf.l_margin

        # ── Cover block ──────────────────────────────────────────
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(20, 20, 80)
        _mcell(pdf, 0, 13, "ResearchForge", lm)

        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(80, 80, 80)
        _mcell(pdf, 0, 7, "Autonomous AI Research Report", lm)
        pdf.ln(2)

        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 100, 100)
        _mcell(pdf, 0, 7, f"Topic: {_clean(query)}", lm)
        _mcell(pdf, 0, 7, f"Date:  {datetime.now().strftime('%B %d, %Y')}", lm)
        pdf.ln(3)

        # Divider
        pdf.set_draw_color(40, 80, 160)
        pdf.set_line_width(0.6)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.set_x(lm)
        pdf.set_line_width(0.2)
        pdf.ln(6)

        # ── Report body ──────────────────────────────────────────
        for line in report.split("\n"):
            s = line.strip()

            if not s or s == "---":
                pdf.ln(2)
                continue

            if s.startswith("# "):
                pdf.set_font("Helvetica", "B", 16)
                pdf.set_text_color(20, 20, 80)
                pdf.ln(2)
                _mcell(pdf, 0, 11, _clean(s[2:]), lm)
                pdf.ln(1)

            elif s.startswith("## "):
                pdf.set_font("Helvetica", "B", 13)
                pdf.set_text_color(40, 80, 160)
                pdf.ln(3)
                _mcell(pdf, 0, 9, _clean(s[3:]), lm)
                y = pdf.get_y()
                pdf.set_draw_color(40, 80, 160)
                pdf.line(10, y, 110, y)
                pdf.set_x(lm)     # reset after line()
                pdf.ln(4)

            elif s.startswith("### "):
                pdf.set_font("Helvetica", "B", 11)
                pdf.set_text_color(60, 60, 60)
                pdf.ln(1)
                _mcell(pdf, 0, 8, _clean(s[4:]), lm)
                pdf.ln(1)

            elif s.startswith(("- ", "* ", "+ ")):
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(50, 50, 50)
                pdf.set_x(lm + 4)
                pdf.multi_cell(0, 6, "-  " + _clean(s[2:]))

            elif re.match(r'^\d+\.', s):
                content = re.sub(r'^\d+\.\s*', '', s)
                num = re.match(r'^(\d+)', s).group(1)
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(50, 50, 50)
                pdf.set_x(lm + 4)
                pdf.multi_cell(0, 6, f"{num}.  {_clean(content)}")

            else:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(50, 50, 50)
                _mcell(pdf, 0, 6, _clean(s), lm)
                pdf.ln(0.5)

        # ── Footer ───────────────────────────────────────────────
        pdf.ln(6)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.set_x(lm)
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(160, 160, 160)
        _mcell(pdf, 0, 5, "Generated by ResearchForge  |  LangGraph + Gemini + Tavily", lm)

        return bytes(pdf.output())

    except Exception as e:
        fallback = f"ResearchForge Report\nTopic: {query}\n\n{report}"
        return fallback.encode('latin-1', errors='replace')


# ── Streamlit UI components ───────────────────────────────────────────────────

def render_header():
    st.markdown("""
        <div style='text-align:center;padding:2rem 0 1rem 0;'>
            <h1 style='font-size:2.6rem;font-weight:800;margin:0;'>🔬 ResearchForge</h1>
            <p style='color:#6b7280;font-size:1.05rem;margin-top:0.4rem;'>
                Autonomous Research Agent &nbsp;·&nbsp; LangGraph + Gemini + Tavily
            </p>
        </div>
    """, unsafe_allow_html=True)


def render_how_it_works():
    cols = st.columns(5)
    steps = [
        ("🧠","Planner",    "Breaks query into 3 tasks"),
        ("🔍","Search",     "Finds web articles"),
        ("📊","Analysis",   "Summarises findings"),
        ("🌍","Examples",   "Finds real companies"),
        ("✍️","Synthesizer","Writes final report"),
    ]
    for col, (icon, title, desc) in zip(cols, steps):
        with col:
            st.markdown(f"""
                <div style='text-align:center;padding:1rem 0.5rem;background:#f9fafb;
                            border-radius:10px;border:1px solid #e5e7eb;'>
                    <div style='font-size:1.8rem;'>{icon}</div>
                    <div style='font-weight:600;margin:0.3rem 0;'>{title}</div>
                    <div style='font-size:0.78rem;color:#6b7280;'>{desc}</div>
                </div>
            """, unsafe_allow_html=True)


def render_agent_status(status_log: list, todos: list):
    st.markdown("### 🤖 Agent Activity")
    color_map = {
        "planner":"#7c3aed","search":"#2563eb","analysis":"#0891b2",
        "examples":"#059669","synthesizer":"#d97706","quality":"#dc2626",
    }
    for entry in status_log:
        color = "#6b7280"
        for kw, c in color_map.items():
            if kw in entry.lower(): color = c; break
        st.markdown(f"""
            <div style='padding:0.45rem 1rem;margin:0.2rem 0;border-left:4px solid {color};
                        background:#f9fafb;border-radius:0 6px 6px 0;font-size:0.88rem;'>
                ✓ {entry}</div>
        """, unsafe_allow_html=True)
    if todos:
        st.markdown("**Task Checklist:**")
        for t in todos:
            icon = "✅" if t["status"] == "done" else "⏳"
            st.markdown(f"{icon} `{t['assigned_to']}` — {t['task']}")


def render_virtual_files(virtual_files: dict):
    st.markdown("### 📁 Agent Output Files")
    icons = {"search_results.txt":"🔍","analysis.txt":"📊","examples.txt":"🌍"}
    for fname, content in virtual_files.items():
        icon = icons.get(fname, "📄")
        with st.expander(f"{icon}  {fname}  ({len(content)} chars)"):
            st.text(content[:2000] + ("..." if len(content) > 2000 else ""))


def render_quality_badge(score):
    if score is None: return
    if score >= 8:   color, label = "#059669", "Excellent"
    elif score >= 6: color, label = "#2563eb", "Good"
    elif score >= 4: color, label = "#d97706", "Fair"
    else:            color, label = "#dc2626", "Low"
    st.markdown(f"""
        <div style='display:inline-flex;align-items:center;gap:0.5rem;padding:0.4rem 1.2rem;
                    border-radius:20px;background:{color}18;border:1px solid {color};margin-bottom:1rem;'>
            <span style='color:{color};font-weight:600;font-size:0.95rem;'>
                ✅ Quality Score: {score}/10 — {label}
            </span>
        </div>
    """, unsafe_allow_html=True)


def render_report(report: str, user_query: str = "Research Report"):
    st.markdown("### 📄 Final Research Report")
    st.markdown(report)
    st.divider()
    col1, col2 = st.columns(2)
    with col1:
        st.download_button(
            label="⬇️ Download as Markdown", data=report,
            file_name="research_report.md", mime="text/markdown",
            use_container_width=True
        )
    with col2:
        pdf_bytes = _generate_pdf(report, user_query)
        st.download_button(
            label="📄 Download as PDF", data=pdf_bytes,
            file_name="research_report.pdf", mime="application/pdf",
            use_container_width=True
        )
